### PR TITLE
Complete jdbc pool test

### PR DESCRIPTION
**Pull request by avpinchuk**
Complete jdbc pool test.

### CODE REVIEW

**Comment by avpinchuk** [comment]
@dmatej, please review when you have time

**Review by dmatej — APPROVED** [review]

**Comment by dmatej** [comment]
Good, it works!

**Comment by dmatej** [comment]
Can you merge it to your branch?

**Comment by dmatej** [comment]
Just for the record, results on my laptop:

```
mvn clean install -pl :connectors-runtime
```
```
Expected: <0>
but: was <25>
[INFO]   Run 5: PASS
[ERROR]   Run 6: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <12>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <12>
[INFO]   Run 7: PASS
[INFO]   Run 8: PASS
[ERROR]   Run 9: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <6>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <6>
[ERROR]   Run 10: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <4>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <4>
[INFO]   Run 11: PASS
[ERROR]   Run 12: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <11>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <11>
[ERROR]   Run 13: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <7>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <7>
[INFO]   Run 14: PASS
[ERROR]   Run 15: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <14>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <14>
[ERROR]   Run 16: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <4>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <4>
[ERROR]   Run 17: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <21>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <21>
[ERROR]   Run 18: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <2>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <2>
[INFO]   Run 19: PASS
[ERROR]   Run 20: RWLockDataStructureTest.raceConditions:112 Multiple Failures (3 failures)
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
java.lang.AssertionError: Resources Size
Expected: <0>
but: was <1>
java.lang.AssertionError: Free list size
Expected: <0>
but: was <1>
[INFO]
[INFO]
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by avpinchuk** [comment]
> Can you merge it to your branch?

Yes, but evening.

> Just for the record, results on my laptop:

This is correct result because `RWLockDataStructure` now incorrect synchronized. This is what I want to achieve - guaranteed reproducibility.

Big thanks for your advice and test class skecth!

**Comment by dmatej** [comment]
It was my pleasure!

**Comment by avpinchuk** [comment]
@dmatej, dumb question - I should merge from your branch or from my branch ccx-test4jdbcpool? How to do it better?

**Comment by dmatej** [comment]
> @dmatej, dumb question - I should merge from your branch or from my branch ccx-test4jdbcpool? How to do it better?

I have created a PR to your branch which is a base for the PR to GlassFish, so if the test passes, we should be done. Does it make sense to you?
https://github.com/avpinchuk/glassfish/pull/1

**Comment by avpinchuk** [comment]
Great, thanks!

**Pull request merged**
